/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.groseryStore.view;

/**
 *
 * @author Paul Mena The Programmers ESPE-DCCO
 */
public class GroseryStore extends javax.swing.JFrame {

    /**
     * Creates new form GroseryStore
     */
    public GroseryStore() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MnuUsers = new javax.swing.JMenu();
        ItmCreateUser = new javax.swing.JMenuItem();
        ItmChangePassword = new javax.swing.JMenuItem();
        MnuProducts = new javax.swing.JMenu();
        ItmBuy = new javax.swing.JMenuItem();
        ItmAdd = new javax.swing.JMenuItem();
        ItmDelete = new javax.swing.JMenuItem();
        MnuBill = new javax.swing.JMenu();
        ItmGenerate = new javax.swing.JMenuItem();
        ItmReview = new javax.swing.JMenuItem();
        MnuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MnuUsers.setText("Users");
        MnuUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnuUsersMouseClicked(evt);
            }
        });

        ItmCreateUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        ItmCreateUser.setText("Create");
        ItmCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmCreateUserActionPerformed(evt);
            }
        });
        MnuUsers.add(ItmCreateUser);

        ItmChangePassword.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        ItmChangePassword.setText("Change Password");
        ItmChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmChangePasswordActionPerformed(evt);
            }
        });
        MnuUsers.add(ItmChangePassword);

        jMenuBar1.add(MnuUsers);

        MnuProducts.setText("Products");

        ItmBuy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        ItmBuy.setText("Buy");
        MnuProducts.add(ItmBuy);

        ItmAdd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        ItmAdd.setText("Add");
        MnuProducts.add(ItmAdd);

        ItmDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        ItmDelete.setText("Delete");
        MnuProducts.add(ItmDelete);

        jMenuBar1.add(MnuProducts);

        MnuBill.setText("Bill");

        ItmGenerate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        ItmGenerate.setText("Generate");
        MnuBill.add(ItmGenerate);

        ItmReview.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK));
        ItmReview.setText("Review");
        MnuBill.add(ItmReview);

        jMenuBar1.add(MnuBill);

        MnuExit.setText("Exit");
        MnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuExitActionPerformed(evt);
            }
        });
        jMenuBar1.add(MnuExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnuUsersMouseClicked
        //System.exit(0);
        //this.dispose();
        
    }//GEN-LAST:event_MnuUsersMouseClicked

    private void ItmCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmCreateUserActionPerformed
        FrmCreateUser frmCreateUser = new FrmCreateUser();
        frmCreateUser.setVisible(true);
    }//GEN-LAST:event_ItmCreateUserActionPerformed

    private void ItmChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmChangePasswordActionPerformed
        FrmChangePassword frmChangePassword = new FrmChangePassword();
        frmChangePassword.setVisible(true);        
    }//GEN-LAST:event_ItmChangePasswordActionPerformed

    private void MnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_MnuExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroseryStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroseryStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroseryStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroseryStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroseryStore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItmAdd;
    private javax.swing.JMenuItem ItmBuy;
    private javax.swing.JMenuItem ItmChangePassword;
    private javax.swing.JMenuItem ItmCreateUser;
    private javax.swing.JMenuItem ItmDelete;
    private javax.swing.JMenuItem ItmGenerate;
    private javax.swing.JMenuItem ItmReview;
    private javax.swing.JMenu MnuBill;
    private javax.swing.JMenu MnuExit;
    private javax.swing.JMenu MnuProducts;
    private javax.swing.JMenu MnuUsers;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
