/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.bookstore.view;

/**
 *
 * @author Steven Achig Future Programmers ESPE-DCCO
 */
public class FrmBookstore extends javax.swing.JFrame {

    /**
     * Creates new form FrmBookstore
     */
    public FrmBookstore() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuExit = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        itmCreate = new javax.swing.JMenuItem();
        itmChange = new javax.swing.JMenuItem();
        mnuProduct = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnuBill = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuExit.setText("Exit");
        mnuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuExitMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuExit);

        jMenu2.setText("Users");

        itmCreate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        itmCreate.setText("Create");
        itmCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCreateActionPerformed(evt);
            }
        });
        jMenu2.add(itmCreate);

        itmChange.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        itmChange.setText("Change Password");
        itmChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmChangeActionPerformed(evt);
            }
        });
        jMenu2.add(itmChange);

        jMenuBar1.add(jMenu2);

        mnuProduct.setText("Product");

        jMenuItem1.setText("Buy");
        mnuProduct.add(jMenuItem1);

        jMenuItem2.setText("Add");
        mnuProduct.add(jMenuItem2);

        jMenuItem3.setText("Delete");
        mnuProduct.add(jMenuItem3);

        jMenuBar1.add(mnuProduct);

        mnuBill.setText("Bill");

        jMenuItem4.setText("Generate");
        mnuBill.add(jMenuItem4);

        jMenuItem5.setText("Review");
        mnuBill.add(jMenuItem5);

        jMenuBar1.add(mnuBill);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_mnuExitMouseClicked

    private void itmChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmChangeActionPerformed
        FrmChange change = new FrmChange();
        change.setVisible(true);
        dispose();
    }//GEN-LAST:event_itmChangeActionPerformed

    private void itmCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCreateActionPerformed
        FrmCreateUser createUser = new FrmCreateUser();
        createUser.setVisible(true);
        dispose();
    }//GEN-LAST:event_itmCreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBookstore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBookstore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBookstore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBookstore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBookstore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmChange;
    private javax.swing.JMenuItem itmCreate;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu mnuBill;
    private javax.swing.JMenu mnuExit;
    private javax.swing.JMenu mnuProduct;
    // End of variables declaration//GEN-END:variables
}
